"""Device health email reports — HTML digest sent via SMTP or printed to stdout."""
from __future__ import annotations

import datetime
import html as _html
import json
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any

from ._paths import HISTORY_FILE

try:
    from .scan import run_scan as run_scan
except Exception:  # scan module may not be present in all installations
    run_scan = None  # type: ignore[assignment]


# ── HTML template ────────────────────────────────────────────────────────────

_CSS = """
body { font-family: 'Red Hat Text', Arial, sans-serif; background: #151515; color: #e0e0e0; margin: 0; padding: 0; }
.wrapper { max-width: 640px; margin: 0 auto; padding: 24px; }
.header { background: #EE0000; color: #fff; padding: 24px 28px; border-radius: 8px 8px 0 0; }
.header h1 { margin: 0; font-size: 22px; font-weight: 700; letter-spacing: -0.3px; }
.header p { margin: 6px 0 0; font-size: 14px; opacity: 0.85; }
.body { background: #1f1f1f; padding: 24px 28px; border-radius: 0 0 8px 8px; }
.summary { display: flex; gap: 16px; margin-bottom: 20px; flex-wrap: wrap; }
.stat { background: #2a2a2a; border-radius: 6px; padding: 14px 18px; flex: 1; min-width: 110px; }
.stat .number { font-size: 28px; font-weight: 700; color: #EE0000; }
.stat .label { font-size: 12px; color: #8a8d90; margin-top: 2px; }
.section-title { font-size: 13px; font-weight: 700; color: #8a8d90; text-transform: uppercase; letter-spacing: 0.8px; margin: 20px 0 10px; }
.finding { background: #2a2a2a; border-left: 3px solid #555; border-radius: 4px; padding: 10px 14px; margin-bottom: 8px; }
.finding.critical { border-left-color: #c00; }
.finding.high { border-left-color: #e07000; }
.finding.medium { border-left-color: #c8a000; }
.finding.low { border-left-color: #4a8; }
.finding .title { font-size: 14px; font-weight: 600; }
.finding .detail { font-size: 12px; color: #8a8d90; margin-top: 3px; }
.fixed-badge { background: #1a3a1a; color: #4a8; border-radius: 3px; font-size: 11px; padding: 1px 6px; margin-left: 6px; }
.footer { text-align: center; margin-top: 20px; font-size: 12px; color: #555; }
.footer a { color: #8a8d90; }
"""

def build_html_report(
    period: str,
    scan_findings: list[dict],
    fixed_findings: list[dict],
    error_count: int,
    period_label: str,
) -> str:
    """Build a full HTML email body."""
    total = len(scan_findings)
    critical_high = sum(1 for f in scan_findings if f.get("severity") in ("critical", "high"))
    fixed = len(fixed_findings)
    now = datetime.datetime.now().strftime("%B %d, %Y")

    # Findings HTML
    findings_html = ""
    for f in scan_findings[:15]:  # cap at 15
        sev = _html.escape(f.get("severity", "info"))
        title = _html.escape(f.get("title", "Unknown"))
        detail = _html.escape(f.get("detail", "")[:120])
        is_fixed = f.get("id") in {x.get("id") for x in fixed_findings}
        badge = '<span class="fixed-badge">&#10003; Fixed</span>' if is_fixed else ""
        findings_html += f'<div class="finding {sev}"><div class="title">{title}{badge}</div><div class="detail">{detail}</div></div>\n'

    if not findings_html:
        findings_html = '<div style="color:#8a8d90;font-size:14px;">No security findings this period. &#127881;</div>'

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><style>{_CSS}</style></head>
<body>
<div class="wrapper">
  <div class="header">
    <h1>errex Device Health Report</h1>
    <p>{period_label} &middot; {now}</p>
  </div>
  <div class="body">
    <div class="summary">
      <div class="stat"><div class="number">{total}</div><div class="label">Issues found</div></div>
      <div class="stat"><div class="number">{critical_high}</div><div class="label">Critical/High</div></div>
      <div class="stat"><div class="number">{fixed}</div><div class="label">Auto-fixed</div></div>
      <div class="stat"><div class="number">{error_count}</div><div class="label">Errors explained</div></div>
    </div>
    <div class="section-title">Security Findings</div>
    {findings_html}
  </div>
  <div class="footer">Generated by <a href="https://github.com/Bsel153/errex">errex</a> &middot; <a href="#">Unsubscribe</a></div>
</div>
</body>
</html>"""


# ── Data gathering ────────────────────────────────────────────────────────────

def _load_history_since(days: int) -> list[dict]:
    """Return history entries from the past N days."""
    if not HISTORY_FILE.exists():
        return []
    cutoff = datetime.datetime.utcnow() - datetime.timedelta(days=days)
    entries = []
    try:
        with open(HISTORY_FILE) as f:
            for line in f:
                try:
                    entry = json.loads(line)
                    ts = entry.get("timestamp", "")
                    if ts and datetime.datetime.fromisoformat(ts.rstrip("Z")) >= cutoff:
                        entries.append(entry)
                except Exception:
                    continue
    except Exception:
        pass
    return entries


def gather_report_data(period: str = "weekly") -> dict:
    """Gather scan findings and history stats for the report period."""
    days = {"daily": 1, "weekly": 7, "monthly": 30}.get(period, 7)
    period_label = {"daily": "Daily", "weekly": "Weekly", "monthly": "Monthly"}.get(period, "Weekly")

    history = _load_history_since(days)
    error_count = len(history)

    # Run a fresh scan (no-explain, fast)
    try:
        if run_scan is None:
            raise RuntimeError("scan module not available")
        result = run_scan()
        scan_findings = [f.to_dict() for f in result.findings]
    except Exception:
        scan_findings = []

    # Fixed findings: load from a scan log if present, else empty
    fixed_path = Path.home() / ".errex_fixes.jsonl"
    fixed_findings: list[dict] = []
    if fixed_path.exists():
        cutoff_dt = datetime.datetime.utcnow() - datetime.timedelta(days=days)
        try:
            with open(fixed_path, encoding="utf-8", errors="replace") as f:
                for line in f:
                    try:
                        entry = json.loads(line)
                        ts = entry.get("timestamp", "")
                        if ts and datetime.datetime.fromisoformat(ts.rstrip("Z")) >= cutoff_dt:
                            fixed_findings.append(entry)
                    except Exception:
                        continue
        except Exception:
            pass

    return {
        "period": period,
        "period_label": period_label,
        "scan_findings": scan_findings,
        "fixed_findings": fixed_findings,
        "error_count": error_count,
    }


# ── Sending ───────────────────────────────────────────────────────────────────

def send_email_report(
    to_addr: str,
    smtp_host: str,
    smtp_port: int,
    smtp_user: str,
    smtp_password: str,
    period: str = "weekly",
    from_addr: str = "errex@localhost",
    use_tls: bool = True,
) -> None:
    """Gather data, build HTML, and send via SMTP."""
    data = gather_report_data(period)
    html = build_html_report(
        period=data["period"],
        scan_findings=data["scan_findings"],
        fixed_findings=data["fixed_findings"],
        error_count=data["error_count"],
        period_label=data["period_label"],
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"errex {data['period_label']} Health Report — {datetime.datetime.now().strftime('%b %d')}"
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.attach(MIMEText(html, "html"))

    ctx = ssl.create_default_context() if use_tls else None
    # Port 465 uses implicit TLS (SMTP_SSL); all others use STARTTLS.
    if use_tls and smtp_port == 465:
        with smtplib.SMTP_SSL(smtp_host, smtp_port, context=ctx) as server:
            if smtp_user:
                server.login(smtp_user, smtp_password)
            server.sendmail(from_addr, to_addr, msg.as_string())
    else:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            if use_tls:
                server.starttls(context=ctx)
            if smtp_user:
                server.login(smtp_user, smtp_password)
            server.sendmail(from_addr, to_addr, msg.as_string())


def print_report(period: str = "weekly", output_file: str | None = None) -> None:
    """Print the HTML report to stdout or a file (for testing/preview)."""
    data = gather_report_data(period)
    html = build_html_report(
        period=data["period"],
        scan_findings=data["scan_findings"],
        fixed_findings=data["fixed_findings"],
        error_count=data["error_count"],
        period_label=data["period_label"],
    )
    if output_file:
        Path(output_file).write_text(html)
        print(f"Report written to {output_file}")
    else:
        print(html)
